.\" SCCS ID: xfclock.1 3.0.0 12/06/1999
.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfclock \- clock and calendar for "The Cholesterol Free Desktop Environment"
.SH SYNOPSYS
.B xfclock
[--display]
.PP
.BI \--display " host:dpy"
specifies the server to connect to.
.PP
.PP
.SH DESCRIPTION
xfclock is provides an analogic clock (widget created as part of the XFce project)
and a calendar (standard GTK+ widget)
.PP
.SH SEE ALSO
xfce, xftree, xfwm, xfpager, xfsound, xfmouse, xfbd, xfclock
.PP
.SH AUTHOR
Olivier Fourdan (fourdan@xfce.org)
.PP
