.\" SCCS ID: xfumed.1 5/5/2001
.TH xfumed 1F "Jasper Huijsmans"
.SH NAME
xfumed \- XFce User Menu Editor
.SH SYNOPSYS
.B xfumed 
is the user menu editor for XFce, the Cholesterol Free Desktop Environment. 
.br
.PP
.SH DESCRIPTION
xfumed operates on the ~/.xfce/xfwm.user_menu file and allows addition of 
items, submenus and separators.
.SH SEE ALSO
xfce, xftree, xfglob, xfwm, xfpager, xfsound, xfmouse, xfbd, xfclock
.PP
.SH AUTHOR
Jasper Huijsmans
