/* ctree icons */
#ifndef __ICONS_H__
#define __ICONS_H__
#include "../xftree/icons/page.xpm"
#include "../xftree/icons/page_html.xpm"
#include "../xftree/icons/dir_close.xpm"
#include "../xftree/icons/dir_pd.xpm"
#include "../xftree/icons/dir_open.xpm"
#include "../xftree/icons/dir_open_dot.xpm"
#include "../xftree/icons/dir_open_hidden.xpm"
#include "../xftree/icons/dir_up.xpm"
#include "../xftree/icons/char_dev.xpm"
#include "../xftree/icons/fifo.xpm"
#include "../xftree/icons/socket.xpm"
#include "../xftree/icons/block_dev.xpm"
#include "../xftree/icons/page_tar.xpm"
#include "../xftree/icons/page_compressed.xpm"
#include "../xftree/icons/page_text.xpm"
#include "../xftree/icons/page_image.xpm"
#include "../xftree/icons/page_audio.xpm"
#include "../xftree/icons/page_core.xpm"
#include "../xftree/icons/page_ps.xpm"
#include "../xftree/icons/page_po.xpm"
#include "../xftree/icons/page_backup.xpm"
#include "../xftree/icons/page_adobe.xpm"
#include "../xftree/icons/page_movie.xpm"
#include "../xftree/icons/package_green.xpm"
#include "../xftree/icons/link_flag.xpm"
#include "../xftree/icons/exe.xpm"
#include "../xftree/icons/exe_file.xpm"
#include "../xftree/icons/stale_lnk.xpm"
#include "../xftree/icons/dir_ro.xpm"
#include "../xftree/icons/dir_ro_open.xpm"
#include "../xftree/icons/dir_ro_open_dot.xpm"
#include "../xftree/icons/dir_ro_open_hidden.xpm"
#include "../xftree/icons/pd.xpm"
/* icons for xfsamba */
#include "../xfsamba/icons/comp1.xpm"
#include "../xfsamba/icons/comp2.xpm"
#include "../xfsamba/icons/wg1.xpm"
#include "../xfsamba/icons/wg2.xpm"
#include "../xfsamba/icons/print.xpm"

#endif
