/* toolbar icons */

#include "icons/new_file.xpm"
#include "icons/new_dir.xpm"
#include "icons/new_win.xpm"
#include "icons/new_rox.xpm"
#include "icons/appinfo.xpm"
#include "icons/closewin.xpm"
#include "icons/delete.xpm"
#include "icons/dotfile.xpm"
#include "icons/home.xpm"
#include "icons/empty_trash.xpm"
#include "icons/trash.xpm"
#include "icons/go_back.xpm"
#include "icons/go_to.xpm"
#include "icons/go_up.xpm"
#include "icons/comp1.xpm"
#include "icons/reload.xpm"
#include "icons/tb_copy.xpm"
#include "icons/tb_find.xpm"
#include "icons/tb_macro.xpm"
#include "icons/tb_paste.xpm"
#include "icons/tb_vsplit.xpm"
#include "icons/tb_cut.xpm"
#include "icons/wg1.xpm"


