.\" SCCS ID: xfglob.1 12/10/2000
.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfglob \- Frontend to glob
.SH SYNOPSYS
.B xfglob 
[--display]
.PP
.TP 6
.BI \--display " host:dpy"
specifies the server to connect to.
.SH DESCRIPTION
xfglob is the file finder of XFce, the Cholesterol Free Desktop Environment.
.SH QUICK REFERENCE
Starting
.I xfglob
will use the home directory as the default root directory
.br
.PP
.SH REQUIREMENTS
.B xfglob requires GNU grep 2.x or higher
.SH SEE ALSO
xfce, xftree, glob, xfwm, xfpager, xfsound, xfmouse, xfbd, xfclock
.PP
.SH AUTHOR
Edscott Wilson Garcia
