#!/bin/sh
#
#  gxfce
#
#  Copyright (C) 1999 Olivier Fourdan (fourdan@xfce.org)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#
# xfce_remove - remove XFCE and restore user config files
#
#

BKUP=$HOME/.xfce_bkup
FILES=".Xclients .xinitrc .xsession .gtkrc"

# Check existance of files to restore

if [ ! -d $BKUP ]; then
	echo No backup directory, nothing to restore !
	exit 1;
fi

for i in $FILES; do
	if [ -f $BKUP/$i ]; then
		mv -f $BKUP/$i $HOME
                echo $HOME/$i restored
	else
		echo Warning: Unable to restore $i
		echo File might have been created on XFce installation.
		echo Answer \'y\' to remove XFce\'s files
		rm -i $HOME/$i
	fi
done

# Remove xfdefs
rm -f $HOME/Desktop/Autostart/xfdefs.py

# Remove directory
rmdir $BKUP

echo Deinstallation complete
exit 0
