.\" SCCS ID: xfprint.1 3.1.0 28/08/1999
.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfprint \- small print wrapper for "The Cholesterol Free Desktop Environment"
.SH SYNOPSYS
.B xfprint
[file]
.PP
.BI file
.PP
specifies the file to print.
.PP
.SH DESCRIPTION
xfprint is a minimalist wrapper to be used as drag and drop action for the XFce
front panel.
.SH ENVIRONMENT VARIABLE
.PP
.I PRINTCMD
set the 'print' command to be used. Usually 'lpr' or 'lp', depending on your system 
(defaults to lpr).
.PP
.SH SEE ALSO
xfce, xftree, xfwm, xfpager, xfsound, xfprint, xfbd, xfclock
.PP
.SH AUTHOR
Olivier Fourdan (fourdan@xfce.org)
.PP
