.\" SCCS ID: xfterm.1 3.1.0 22/09/1999
.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfterm \- small terminal wrapper for "The Cholesterol Free Desktop Environment"
.SH SYNOPSYS
.B xfterm
[file]
.PP
.BI file
.PP
specifies the file or directory to open up in a terminal.
.PP
.SH DESCRIPTION
xfterm is a wrapper to be used as drag and drop action for the XFce/XFTree
front panel.
.SH ENVIRONMENT VARIABLE
.PP
.I TERMCMD
set the 'terminal' command to be used. Usually 'xterm'. The terminal emulation 
should support the "-e" option for executing commands
.PP
.SH SEE ALSO
xfce, xftree, xfwm, xfpager, xfsound, xfprint, xfbd, xfclock
.PP
.SH AUTHOR
Joakim Andreasson (karanne@flashback.net)
.PP
